import React, { useState, useEffect } from 'react';
import { Card, FormField, Loader } from '../components';

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />)
  }
  return (
    <h2 className='mt-2 font-bold text-[#6449ff] text-xl uppercase'>{title}</h2>
  )
}

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);

  const [searchText, setsearchText] = useState('')

  return (
    <section className='max-w-7xl mx-auto'>

      <div className="">
        <h1 className='font-extrabold text-3xl text-[#222328]'>The Community Showcase</h1>
        <p className='text-[#666e75] mt-2'>Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
      </div>

      <div className="mt-16">
        <FormField />
      </div>

      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="text-[#666e75] font-medium">
                Showing results for <span className='text-[#222328]'>{searchText}</span>
              </h2>
            )}
            <div className="grid lg:grid-cols-4 md:grid-cols-3 sm:grid-cols-2 xs:grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards
                  data={[]}
                  title="No search results found" />)
                : (<RenderCards
                  data={[]}
                  title="No posts found"
                />)
              }
            </div>
          </>
        )
        }
      </div>

    </section>
  )
}

export default Home
